language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
    - julia -e 'cd(Pkg.dir("MolecularBoxes")); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

